server.port: 8090

kafka:
  custom:
    config:
      source: MSKTutorialTestTopic
      reponse: MSKTutorialTestResponseTopic
      application-id: tsb-fl-restproxy-eligibilitystart
      bootstrap-server: b-2.msktutorialcluster.t5xcsq.c21.kafka.us-east-1.amazonaws.com:9092
      zookeeper-server: z-3.msktutorialcluster.t5xcsq.c21.kafka.us-east-1.amazonaws.com:2181